# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _AWS

class _Accounts(_AWS):
    _type = "accounts"
    _icon_dir = "resources/aws/accounts"


class Account(_Accounts):
    _icon = "account.png"
class OrganizationalUnit(_Accounts):
    _icon = "organizational-unit.png"
class Organizations(_Accounts):
    _icon = "organizations.png"

# Aliases
